import { faAngellist } from '@fortawesome/free-brands-svg-icons'
import {
  faAlignCenter,
  faAlignLeft,
  faAlignRight,
  faArrowDown,
  faArrowRight,
  faArrowUp,
  faBold,
  faFile,
  faFloppyDisk,
  faFolderOpen,
  faFont,
  faGear,
  faItalic,
  faList,
  faListOl,
  faPaste,
  faPenToSquare,
  faPerson,
  faSubscript,
  faSuperscript,
  faTextSlash,
  faUnderline,
} from '@fortawesome/free-solid-svg-icons'

export const Icons = {
  underline: faUnderline,
  bold: faBold,
  align_center: faAlignCenter,
  align_left: faAlignLeft,
  align_right: faAlignRight,
  angel: faAngellist,
  file: faFile,
  paste: faPaste,
  account: faPerson,
  gear: faGear,
  editor: faPenToSquare,
  open: faFolderOpen,
  save: faFloppyDisk,
  save_as: faArrowRight,
  arrow_up: faArrowUp,
  arrow_down: faArrowDown,
  text_deformat: faTextSlash,
  italic: faItalic,
  subscript: faSubscript,
  superscript: faSuperscript,
  font: faFont,
  point_list: faList,
  number_list: faListOl,
}
